common: &common
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  encoding: utf8
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  timeout: 5000
  prepared_statements: false
  
production:
  <<: *common
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *common
  database: <%= ENV['TEST_DATABASE_NAME'] %>

test:
  <<: *common
  database: canvas_test_rails3_<%= ENV['TEST_ENV_NUMBER'] %>
  shard1: canvas_test_rails3_shard1
  shard2: canvas_test_rails3_shard2
  test_shard_1: canvas_test_rails3_shard1
  test_shard_2: canvas_test_rails3_shard2